"""initial production schema

Revision ID: 8b2997af9b5f
Revises: 
Create Date: 2026-08-06 13:36:54.984108

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b2997af9b5f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('areas',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('slug', sa.String(length=30), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('domain_events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('area_slug', sa.String(length=30), nullable=True),
    sa.Column('event_type', sa.String(length=80), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_domain_events_area_slug'), ['area_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_domain_events_created_at'), ['created_at'], unique=False)

    op.create_table('rate_limit_buckets',
    sa.Column('bucket_key', sa.String(length=128), nullable=False),
    sa.Column('window_started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('blocked_until', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('attempt_count >= 0', name='ck_rate_limit_attempt_count_nonnegative'),
    sa.PrimaryKeyConstraint('bucket_key')
    )
    op.create_table('security_events',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('event_type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=20), nullable=False),
    sa.Column('username_hint', sa.String(length=120), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=1024), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_security_events_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_security_events_event_type'), ['event_type'], unique=False)

    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('display_name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('failed_attempts', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('failed_attempts >= 0', name='ck_users_failed_attempts_nonnegative'),
    sa.CheckConstraint('session_version >= 1', name='ck_users_session_version_positive'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('username', sa.String(length=120), nullable=False),
    sa.Column('area_slug', sa.String(length=30), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=80), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('result', sa.String(length=30), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=False),
    sa.Column('user_agent', sa.String(length=1024), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_area_slug'), ['area_slug'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)

    op.create_table('budget_versions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('area_id', sa.String(length=36), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('is_seed', sa.Boolean(), nullable=False),
    sa.Column('source_name', sa.String(length=255), nullable=False),
    sa.Column('source_checksum', sa.String(length=64), nullable=False),
    sa.Column('total_budget', sa.BigInteger(), nullable=False),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('total_budget >= 0', name='ck_budget_versions_total_nonnegative'),
    sa.CheckConstraint('version_number >= 1', name='ck_budget_versions_version_positive'),
    sa.CheckConstraint('year BETWEEN 2020 AND 2100', name='ck_budget_versions_year'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('area_id', 'year', 'version_number', name='uq_budget_version_number')
    )
    with op.batch_alter_table('budget_versions', schema=None) as batch_op:
        batch_op.create_index('ix_budget_active_area_year', ['area_id', 'year', 'active'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_versions_active'), ['active'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_versions_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_versions_year'), ['year'], unique=False)
        batch_op.create_index('uq_budget_one_active_per_area_year', ['area_id', 'year'], unique=True, postgresql_where=sa.text('active'), sqlite_where=sa.text('active = 1'))

    op.create_table('import_preview_cache',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('area_slug', sa.String(length=30), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('checksum', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('import_preview_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_import_preview_cache_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_import_preview_cache_user_id'), ['user_id'], unique=False)

    op.create_table('requirements',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('legacy_id', sa.String(length=100), nullable=True),
    sa.Column('area_id', sa.String(length=36), nullable=False),
    sa.Column('budget_year', sa.Integer(), nullable=False),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('expedient', sa.String(length=120), nullable=False),
    sa.Column('subject', sa.String(length=1000), nullable=False),
    sa.Column('amount', sa.BigInteger(), nullable=False),
    sa.Column('department', sa.String(length=250), nullable=False),
    sa.Column('management_area', sa.String(length=250), nullable=False),
    sa.Column('notes', sa.Text(), nullable=False),
    sa.Column('account_code', sa.String(length=40), nullable=False),
    sa.Column('included_in_base', sa.Boolean(), nullable=False),
    sa.Column('source_file', sa.String(length=255), nullable=True),
    sa.Column('source_row', sa.Integer(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('lock_user_id', sa.String(length=36), nullable=True),
    sa.Column('lock_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=36), nullable=True),
    sa.Column('updated_by', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint('amount > 0', name='ck_requirements_amount_positive'),
    sa.CheckConstraint('budget_year BETWEEN 2020 AND 2100', name='ck_requirements_year'),
    sa.CheckConstraint('version >= 1', name='ck_requirements_version_positive'),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['lock_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['updated_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('legacy_id')
    )
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_requirements_account_code'), ['account_code'], unique=False)
        batch_op.create_index('ix_requirements_active', ['area_id', 'deleted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_area_id'), ['area_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_budget_year'), ['budget_year'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_expedient'), ['expedient'], unique=False)
        batch_op.create_index('ix_requirements_filters', ['area_id', 'budget_year', 'account_code', 'request_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_requirements_request_date'), ['request_date'], unique=False)

    op.create_table('sessions',
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('csrf_hash', sa.String(length=64), nullable=False),
    sa.Column('user_agent_hash', sa.String(length=64), nullable=False),
    sa.Column('ip_created', sa.String(length=64), nullable=False),
    sa.Column('last_ip', sa.String(length=64), nullable=False),
    sa.Column('session_version', sa.Integer(), nullable=False),
    sa.Column('idle_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('absolute_expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('token_hash')
    )
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sessions_absolute_expires_at'), ['absolute_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_idle_expires_at'), ['idle_expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('user_areas',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('area_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['areas.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'area_id')
    )
    op.create_table('budget_accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('budget_version_id', sa.String(length=36), nullable=False),
    sa.Column('code', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=500), nullable=False),
    sa.Column('matrix_code', sa.String(length=40), nullable=False),
    sa.Column('parent_code', sa.String(length=40), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('budget', sa.BigInteger(), nullable=False),
    sa.Column('base_new_requirements', sa.BigInteger(), nullable=False),
    sa.Column('obligated_cas', sa.BigInteger(), nullable=False),
    sa.Column('row_version', sa.Integer(), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint('base_new_requirements >= 0', name='ck_budget_accounts_new_nonnegative'),
    sa.CheckConstraint('budget >= 0', name='ck_budget_accounts_budget_nonnegative'),
    sa.CheckConstraint('level >= 0', name='ck_budget_accounts_level_nonnegative'),
    sa.CheckConstraint('obligated_cas >= 0', name='ck_budget_accounts_cas_nonnegative'),
    sa.CheckConstraint('row_version >= 1', name='ck_budget_accounts_version_positive'),
    sa.ForeignKeyConstraint(['budget_version_id'], ['budget_versions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('budget_version_id', 'code', name='uq_budget_account_code')
    )
    with op.batch_alter_table('budget_accounts', schema=None) as batch_op:
        batch_op.create_index('ix_budget_account_catalog', ['budget_version_id', 'matrix_code', 'code'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_accounts_budget_version_id'), ['budget_version_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_budget_accounts_matrix_code'), ['matrix_code'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('budget_accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_budget_accounts_matrix_code'))
        batch_op.drop_index(batch_op.f('ix_budget_accounts_budget_version_id'))
        batch_op.drop_index('ix_budget_account_catalog')

    op.drop_table('budget_accounts')
    op.drop_table('user_areas')
    with op.batch_alter_table('sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sessions_user_id'))
        batch_op.drop_index(batch_op.f('ix_sessions_idle_expires_at'))
        batch_op.drop_index(batch_op.f('ix_sessions_absolute_expires_at'))

    op.drop_table('sessions')
    with op.batch_alter_table('requirements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_requirements_request_date'))
        batch_op.drop_index('ix_requirements_filters')
        batch_op.drop_index(batch_op.f('ix_requirements_expedient'))
        batch_op.drop_index(batch_op.f('ix_requirements_budget_year'))
        batch_op.drop_index(batch_op.f('ix_requirements_area_id'))
        batch_op.drop_index('ix_requirements_active')
        batch_op.drop_index(batch_op.f('ix_requirements_account_code'))

    op.drop_table('requirements')
    with op.batch_alter_table('import_preview_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_import_preview_cache_user_id'))
        batch_op.drop_index(batch_op.f('ix_import_preview_cache_expires_at'))

    op.drop_table('import_preview_cache')
    with op.batch_alter_table('budget_versions', schema=None) as batch_op:
        batch_op.drop_index('uq_budget_one_active_per_area_year', postgresql_where=sa.text('active'), sqlite_where=sa.text('active = 1'))
        batch_op.drop_index(batch_op.f('ix_budget_versions_year'))
        batch_op.drop_index(batch_op.f('ix_budget_versions_area_id'))
        batch_op.drop_index(batch_op.f('ix_budget_versions_active'))
        batch_op.drop_index('ix_budget_active_area_year')

    op.drop_table('budget_versions')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_area_slug'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))

    op.drop_table('audit_logs')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))

    op.drop_table('users')
    with op.batch_alter_table('security_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_security_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_security_events_created_at'))

    op.drop_table('security_events')
    op.drop_table('rate_limit_buckets')
    with op.batch_alter_table('domain_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_domain_events_created_at'))
        batch_op.drop_index(batch_op.f('ix_domain_events_area_slug'))

    op.drop_table('domain_events')
    op.drop_table('areas')
    # ### end Alembic commands ###
